# Generated by Django 2.1.7 on 2019-03-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=4)),
                ('ename', models.CharField(max_length=20)),
                ('eaccountno', models.IntegerField(max_length=20)),
                ('ephoneno', models.IntegerField(max_length=20)),
            ],
        ),
    ]
