# Generated by Django 2.1.7 on 2019-03-07 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 5, 8, 54, 780390, tzinfo=utc)),
        ),
    ]
