# Generated by Django 2.1.7 on 2019-03-13 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_auto_20190307_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 4, 8, 59, 571722, tzinfo=utc)),
        ),
    ]
